# Generated by Django 5.2.10 on 2026-06-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='gender',
            field=models.CharField(choices=[('Boys', 'Boys Only'), ('Girls', 'Girls Only'), ('Unisex', 'Unisex')], default='Unisex', max_length=15),
        ),
    ]
