# Generated by Django 5.2.10 on 2026-06-14 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_property_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrequest',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_requests', to='rentals.room'),
        ),
    ]
