# Generated by Django 5.2.10 on 2026-06-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
