# Generated by Django 5.2.10 on 2026-06-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0010_globalnotification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
