# Generated by Django 5.2.10 on 2026-06-16 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0012_property_deposit_room_deposit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_inquiries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
