# Generated by Django 5.2.10 on 2026-06-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0013_supportinquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
