# Generated by Django 5.2.10 on 2026-06-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0014_ownerprofile_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobanner',
            name='badge_text',
            field=models.CharField(blank=True, default='Verified Properties', max_length=100),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='feature_1',
            field=models.CharField(blank=True, default='No Hidden Charges', max_length=100),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='feature_2',
            field=models.CharField(blank=True, default='Verified Properties', max_length=100),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='feature_3',
            field=models.CharField(blank=True, default='Direct Owner', max_length=100),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='feature_4',
            field=models.CharField(blank=True, default='Trusted by Thousands', max_length=100),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='localities',
            field=models.CharField(blank=True, default='HSR Layout, Koramangala, BTM Layout, Whitefield, Electronic City', help_text='Comma-separated list of popular localities', max_length=255),
        ),
    ]
