# Generated by Django 5.2.10 on 2026-06-17 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0015_herobanner_badge_text_herobanner_feature_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalnotification',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Leave blank to make this notification global (visible to all logged-in users).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
