# Generated by Django 5.2.10 on 2026-06-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0017_property_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='balcony',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='bathroom',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='furnishing',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
