# Generated by Django 5.2.10 on 2026-08-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0018_room_balcony_room_bathroom_room_furnishing'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.PositiveIntegerField(default=1, help_text='Floor number e.g. 1, 2, 3'),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
