# Generated by Django 5.2.10 on 2026-08-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0020_alter_property_amenities_alter_property_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Floor number e.g. 1, 2, 3', null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
