# Generated by Django 5.2.10 on 2026-08-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0021_alter_room_floor_alter_room_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='APPROVED', max_length=20),
        ),
    ]
