# Generated by Django 5.2.10 on 2026-08-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0022_alter_visitrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
